;; NNL2

;; Filepath: nnl2/src/lisp/highlevel/highlevel-package.lisp
;; File: highlevel-package.lisp

;; Definition of :nnl2.hli, :nnl2.hli.ts, :nnl2.hli.ad
;; packages where hli stays for high-level-interface, 
;; ts stays for tensor system, ad stays for automatic 
;; differentiation

;; UPD: also definition of :nnl2.hli.nn package
;; where nn i think is autologous

;; UPD: also added definition of ```:nnl2.hli.ts.loss, :nnl2.hli.ad.r.loss, 
;; :nnl2.hli.nn.ga, :nnl2.hli.nn.ga.fitness, :nnl2.hli.nn.ga.crossover,
;; :nnl2.hli.nn.ga.mutation, :nnl2.hli.nn.ga.selection, nnl2.hli.ts.linalg``` packages

;; In case of errors/problems/suggestions, please write to issues or nnl.dev@proton.me
;; nnl2 Repository: https://github.com/danish-song-of-liberation/nnl2

(defpackage #:nnl2.hli.nn.ga.selection
  (:use #:cl)
  (:export 
    #:tournament
	#:elitist))

(defpackage #:nnl2.hli.nn.ga.mutation
  (:use #:cl)
  (:export
    #:uniform))

(defpackage #:nnl2.hli.nn.ga.crossover
  (:use #:cl)
  (:export
    #:uniform))
	
(defpackage #:nnl2.hli.nn.ga.fitness
  (:use #:cl)
  (:export
    #:mse))

(defpackage #:nnl2.hli.nn.ga
  (:use #:cl)
  (:export
    #:encode-cons
    #:encode
	#:encoder-with-vector
	#:decode
	#:print-encoder
	#:free-encoder))

(defpackage #:nnl2.hli.nn
  (:use #:cl)
  (:export
   #:fnn
   #:rnncell
   #:free
   #:forward
   #:nnlet
   #:nnlet*
   #:parameters
   #:*nn-default-init-type*
   #:sequential
   #:.sigmoid
   #:.tanh
   #:.relu
   #:.leaky-relu
   #:print-model
   #:copy
   #:nnp
   #:rnn))

(defpackage #:nnl2.hli
  (:use #:cl)
  (:export 
   #:make-foreign-pointer
   #:fastcall
   #:make-shape-pntr
   #:free-shape-pntr
   #:with-automatic-memory-freeing
   #:reduce-list-shape
   #:flatten
   #:reduce-list-size
   #:list-to-flat-vector-and-shape
   #:->
   #:<-
   #:stypeof))
   
(defpackage #:nnl2.hli.ad
  (:use #:cl)
  (:export
   #:empty
   #:zeros
   #:ones
   #:data
   #:rank
   #:shape
   #:full
   #:free
   #:is-leaf
   #:requires-grad
   #:grad
   #:backpropagation
   #:bp
   #:backpropagation-through-time
   #:bptt
   #:tlet
   #:tlet*
   #:with-tensor-dispatch
   #:print-data
   #:print-grad
   #:shapes-equal-p
   #:object-type
   #:zero-grad!
   #:dtype
   #:int-dtype
   #:.+/ad/incf!
   #:+=/ad/incf!
   #:.*/ad/mulf!
   #:*=/ad/mulf!
   #:.-/ad/decf!
   #:-=/ad/decf!
   #:./ad/divf!
   #:/!/ad/divf!
   #:.^/ad/powf!
   #:^=/ad/powf!
   #:.min/ad/minf!
   #:.min!/ad/minf!
   #:.max/ad/maxf!
   #:.max!/ad/maxf!
   #:axpy/ad/axpf!
   #:axpy!/ad/axpf!
   #:.atan2/ad/correspondence
   #:.atan2/ad/correspondence!
   #:.neg!
   #:+=
   #:-=
   #:*=
   #:/!
   #:^=
   #:.abs!
   #:.min!
   #:.max!
   #:axpy!
   #:scale!
   #:.exp!
   #:.log!
   #:.relu!
   #:.leaky-relu!
   #:.sigmoid!
   #:.tanh!
   #:step-ts
   #:step!
   #:num-roots
   #:roots
   #:uniform
   #:xavier
   #:transposition!
   #:transpose!
   #:.sqrt!
   #:copy
   #:with-notrack
   #:empty-like
   #:zeros-like
   #:ones-like
   #:full-like
   #:uniform-like
   #:xavier-like
   #:ncast
   #:detach!
   #:detach
   #:make-tensor
   #:from-flatten
   #:strides
   #:name
   #:nrows
   #:ncols
   #:rand
   #:randn
   #:rand-like
   #:randn-like
   #:kaiming
   #:kaiming-like
   #:.sin!
   #:.cos!
   #:.asin!
   #:.acos!
   #:.atan!
   #:.tan!
   #:.atan2!
   #:.square!
   #:.cube!
   #:.log10!
   #:.log2!
   #:.log1p!))
   
(defpackage #:nnl2.hli.ad.r
  (:use #:cl)
  (:export
   #:.+
   #:.-
   #:.*
   #:./
   #:.^
   #:.abs
   #:gemm
   #:gemmvp
   #:.min
   #:.max
   #:axpy
   #:.exp
   #:.log
   #:scale
   #:.relu
   #:.leaky-relu
   #:.sigmoid
   #:.tanh
   #:.neg
   #:transpose
   #:transposition
   #:reshape
   #:reinterpret
   #:.sqrt
   #:slice
   #:norm
   #:sum
   #:vstack
   #:hstack
   #:concat
   #:view
   #:tref
   #:.sin
   #:.cos
   #:.asin
   #:.acos
   #:.atan
   #:.tan
   #:.atan2
   #:.square
   #:.cube
   #:.log
   #:.log10
   #:.log2
   #:.log1p))   
 
(defpackage #:nnl2.hli.ad.r.loss
  (:use #:cl)
  (:export
   #:mse
   #:mae))  
 
(defpackage #:nnl2.hli.ts.loss
  (:use #:cl)
  (:export
   #:mse
   #:mae))  

(defpackage #:nnl2.hli.ts
  (:use #:cl)
  (:export 
   #:kaiming
   #:empty
   #:zeros
   #:zeros-with-pntr
   #:ones
   #:ones-with-pntr
   #:tlet
   #:full
   #:full-with-pntr
   #:print-tensor
   #:rank
   #:strides
   #:dtype
   #:int-dtype
   #:gemmvp
   #:reshape
   #:reinterpret
   #:shape-pointer
   #:shape
   #:.log!
   #:.log
   #:gemm
   #:gemm!
   #:+=
   #:-=
   #:numel
   #:size-in-bytes
   #:process-to-indices
   #:.+
   #:.-
   #:*=
   #:/!
   #:.*
   #:./
   #:^=
   #:.^
   #:.exp!
   #:.exp
   #:tref
   #:view
   #:scale!
   #:scale
   #:zeros-like
   #:ones-like
   #:full-like
   #:.max!
   #:.min!
   #:.max
   #:kaiming-like
   #:.min
   #:.abs!
   #:.abs
   #:.map!
   #:empty-like
   #:xavier-like
   #:.map
   #:hstack
   #:vstack
   #:tlet*
   #:.relu!
   #:.relu
   #:.leaky-relu!
   #:.leaky-relu
   #:.sigmoid!
   #:.sigmoid
   #:.tanh!
   #:.tanh
   #:concat
   #:xavier
   #:transpose!
   #:transpose
   #:sum
   #:norm
   #:copy
   #:ncast
   #:.+/incf!
   #:.+/incf
   #:.-/decf!
   #:.-/decf
   #:.+/gnrl
   #:.+/gnrl!
   #:.-/gnrl
   #:.-/gnrl!
   #:.*/mulf!
   #:.*/mulf
   #:.//divf!
   #:.//divf
   #:.*/gnrl!
   #:.*/gnrl
   #:.//gnrl!
   #:.//gnrl
   #:.^/powf!
   #:.^/powf
   #:.^/gnrl!
   #:.^/gnrl
   #:.max/maxf!
   #:.max/gnrl!
   #:.max/maxf
   #:.max/gnrl
   #:.min/minf!
   #:.min/gnrl!
   #:.min/minf
   #:.min/gnrl
   #:.+/broadcasting!
   #:.+/broadcasting
   #:.-/broadcasting
   #:.-/broadcasting!
   #:.*/broadcasting!
   #:.*/broadcasting
   #:.//broadcasting!
   #:.//broadcasting
   #:.^/broadcasting!
   #:.^/broadcasting
   #:*nnl2-tensor-types*
   #:ts-type-to-lisp
   #:lisp-type-to-ts
   #:from-flatten
   #:make-tensor
   #:/map
   #:/map!
   #:axpy
   #:axpy!
   #:use-backend
   #:use-backend/tref
   #:use-backend/abs
   #:use-backend/inplace-fill
   #:use-backend/+=
   #:use-backend/-=
   #:use-backend/*=
   #:use-backend//!
   #:use-backend/^=
   #:use-backend/.log!
   #:use-backend/.max!
   #:use-backend/.min!
   #:use-backend/scale!
   #:use-backend/.+
   #:use-backend/.-
   #:use-backend/.*
   #:use-backend/./
   #:use-backend/.^
   #:use-backend/.log
   #:use-backend/.min
   #:use-backend/.max
   #:use-backend/scale
   #:use-backend/gemm
   #:use-backend/empty
   #:use-backend/empty-like
   #:use-backend/.abs
   #:use-backend/xavier
   #:use-backend/uniform
   #:use-backend/uniform-like
   #:use-backend/full
   #:use-backend/ones
   #:use-backend/full-like
   #:use-backend/zeros
   #:use-backend/zeros-like
   #:use-backend/sum
   #:use-backend/l2norm
   #:use-backend/copy
   #:use-backend/.relu
   #:use-backend/.relu!
   #:use-backend/.leaky-relu
   #:use-backend/.leaky-relu!
   #:use-backend/.sigmoid
   #:use-backend/.sigmoid!
   #:use-backend/.tanh
   #:use-backend/.tanh!
   #:use-backend/transpose
   #:use-backend/transpose!
   #:use-backend/reshape
   #:use-backend/reinterpret
   #:use-backend/slice
   #:use-backend/transposition
   #:use-backend/transposition!
   #:get-backend/view
   #:get-backend/tref
   #:get-backend/empty
   #:get-backend/zeros
   #:get-backend/ones
   #:get-backend/full
   #:get-backend/empty-like
   #:get-backend/zeros-like
   #:get-backend/ones-like
   #:get-backend/full-like
   #:get-backend/gemm
   #:get-backend/gemm!
   #:get-backend/+=
   #:get-backend/-=
   #:get-backend/.+
   #:get-backend/.-
   #:get-backend/*=
   #:get-backend//!
   #:get-backend/.*
   #:get-backend/./
   #:get-backend/^=
   #:get-backend/.^
   #:get-backend/.exp!
   #:get-backend/.exp
   #:get-backend/.log!
   #:get-backend/.log
   #:get-backend/scale!
   #:get-backend/scale
   #:get-backend/.max!
   #:get-backend/.max
   #:get-backend/.min!
   #:get-backend/.min
   #:get-backend/.abs!
   #:get-backend/.abs
   #:get-backend/hstack
   #:get-backend/vstack
   #:get-backend/.relu!
   #:get-backend/.relu
   #:get-backend/.leaky-relu!
   #:get-backend/.leaky-relu
   #:get-backend/.sigmoid
   #:get-backend/.sigmoid!
   #:get-backend/.tanh
   #:get-backend/.tanh!
   #:get-backend/concat
   #:get-backend/uniform
   #:get-backend/uniform-like
   #:get-backend/xavier
   #:get-backend/transpose
   #:get-backend/transpose!
   #:get-backend/sum
   #:get-backend/norm
   #:get-backend/copy
   #:get-backend/axpy!
   #:get-backend/axpy
   #:get-backend/reshape
   #:get-backend/reinterpret
   #:get-backend/slice
   #:get-backend/transposition
   #:get-backend/transposition!
   #:get-backends/tref
   #:get-backends/view
   #:get-backends/empty
   #:get-backends/zeros
   #:get-backends/full
   #:get-backends/ones
   #:get-backends/empty-like
   #:get-backends/zeros-like
   #:get-backends/full-like
   #:get-backends/ones-like
   #:get-backends/gemm
   #:get-backends/gemm!
   #:get-backends/+=
   #:get-backends/-=
   #:get-backends/.+
   #:get-backends/.-
   #:get-backends/*=
   #:get-backends//!
   #:get-backends/.*
   #:get-backends/./
   #:get-backends/^=
   #:get-backends/.^
   #:get-backends/.exp!
   #:get-backends/.exp
   #:get-backends/.log!
   #:get-backends/.log
   #:get-backends/scale
   #:get-backends/scale!
   #:get-backends/.max!
   #:get-backends/.min!
   #:get-backends/.max
   #:get-backends/.min
   #:get-backends/.abs
   #:get-backends/.abs!
   #:get-backends/hstack
   #:get-backends/vstack
   #:get-backends/.relu
   #:get-backends/.relu!
   #:get-backends/.leaky-relu
   #:get-backends/.leaky-relu!
   #:get-backends/.sigmoid
   #:get-backends/.sigmoid!
   #:get-backends/.tanh
   #:get-backends/.tanh!
   #:get-backends/concat
   #:get-backends/uniform
   #:get-backends/uniform-like
   #:get-backends/xavier
   #:get-backends/transpose!
   #:get-backends/transpose
   #:get-backends/sum
   #:get-backends/norm
   #:get-backends/copy
   #:get-backends/axpy!
   #:get-backends/axpy
   #:get-backends/reshape
   #:get-backends/reinterpret
   #:get-backends/slice
   #:get-backends/transposition
   #:get-backends/transposition!
   #:with-backend/view
   #:with-backend/tref
   #:with-backend/full
   #:with-backend/ones
   #:with-backend/zeros
   #:with-backend/empty
   #:with-backend/full-like
   #:with-backend/ones-like
   #:with-backend/zeros-like
   #:with-backend/empty-like
   #:with-backend/gemm
   #:with-backend/gemm!
   #:with-backend/.+
   #:with-backend/.-
   #:with-backend/+=
   #:with-backend/-=
   #:with-backend/*=
   #:with-backend//!
   #:with-backend/.exp!
   #:with-backend/.exp
   #:with-backend/.log!
   #:with-backend/.log
   #:with-backend/scale!
   #:with-backend/scale
   #:with-backend/.max!
   #:with-backend/.min!
   #:with-backend/.max
   #:with-backend/.min
   #:with-backend/.abs!
   #:with-backend/.abs
   #:with-backend/hstack
   #:with-backend/vstack
   #:with-backend/.relu
   #:with-backend/.relu!
   #:with-backend/.leaky-relu
   #:with-backend/.leaky-relu!
   #:with-backend/.sigmoid
   #:with-backend/.sigmoid!
   #:with-backend/.tanh
   #:with-backend/.tanh!
   #:with-backend/concat
   #:with-backend/uniform
   #:with-backend/uniform-like
   #:with-backend/xavier
   #:with-backend/transpose!
   #:with-backend/transpose
   #:with-backend/sum
   #:with-backend/norm
   #:with-backend/copy
   #:with-backend/axpy!
   #:with-backend/axpy
   #:with-backend/reshape
   #:with-backend/reinterpret
   #:with-backend/slice
   #:with-backend/transposition
   #:with-backend/transposition!
   #:tensor-p
   #:type/nnl2->lisp
   #:type/lisp->nnl2
   #:type/nnl2->cffi
   #:type/lisp->cffi
   #:free
   #:empty-with-shape-pntr
   #:slice
   #:nrows
   #:ncols
   #:transposition
   #:transposition!
   #:fill!
   #:use-backend/axpy!
   #:use-backend/axpy
   #:any-scalar-p
   #:shapes-equal-p
   #:higher-rank-tensor
   #:both-scalars-p
   #:.neg!
   #:use-backend/.neg!
   #:get-backend/.neg!
   #:get-backends/.neg!
   #:with-backend/.neg!
   #:.neg
   #:get-backends/.neg
   #:get-backend/.neg
   #:with-backend/.neg
   #:use-backend/.neg
   #:use-backend/uniform!
   #:get-backend/uniform!
   #:get-backends/uniform!
   #:with-backend/uniform!
   #:xavier!
   #:use-backend/xavier!
   #:get-backend/xavier!
   #:get-backends/xavier!
   #:with-backend/xavier!
   #:.sqrt
   #:.sqrt!
   #:use-backend/.sqrt!
   #:use-backend/.sqrt
   #:get-backend/.sqrt!
   #:get-backend/.sqrt
   #:get-backends/.sqrt!
   #:get-backends/.sqrt
   #:with-backend/.sqrt!
   #:with-backend/.sqrt
   #:use-backend/mse
   #:get-backend/mse
   #:use-backend/mse
   #:get-backends/mse
   #:with-backend/mse
   #:uniform
   #:uniform!
   #:uniform-like
   #:rand
   #:rand!
   #:with-backend/rand
   #:with-backend/rand!
   #:get-backends/rand
   #:get-backends/rand!
   #:get-backend/rand
   #:use-backend/rand
   #:get-backend/rand!
   #:use-backend/rand!
   #:randn
   #:randn!
   #:use-backend/randn
   #:use-backend/randn!
   #:get-backend/randn
   #:get-backend/randn!
   #:get-backends/randn
   #:get-backends/randn!
   #:with-backend/randn
   #:with-backend/randn!
   #:rand-like
   #:randn-like
   #:kaiming!
   #:use-backend/kaiming
   #:use-backend/kaiming!
   #:get-backend/kaiming
   #:get-backend/kaiming!
   #:get-backends/kaiming
   #:get-backends/kaiming!
   #:with-backend/kaiming
   #:with-backend/kaiming!
   #:.sin!
   #:.cos!
   #:.sin
   #:.cos
   #:use-backend/.cos
   #:use-backend/.cos!
   #:use-backend/.sin
   #:use-backend/.sin!
   #:get-backend/.cos
   #:get-backend/.sin
   #:get-backend/.cos!
   #:get-backend/.sin!
   #:get-backends/.cos!
   #:get-backends/.cos
   #:get-backends/.sin!
   #:get-backends/.sin
   #:with-backend/.cos!
   #:with-backend/.cos
   #:with-backend/.sin!
   #:with-backend/.sin
   #:.asin!
   #:.acos!
   #:.asin
   #:.acos
   #:use-backend/.acos
   #:use-backend/.acos!
   #:use-backend/.asin
   #:use-backend/.asin!
   #:get-backend/.acos
   #:get-backend/.asin
   #:get-backend/.acos!
   #:get-backend/.asin!
   #:get-backends/.acos!
   #:get-backends/.acos
   #:get-backends/.asin!
   #:get-backends/.asin
   #:with-backend/.acos!
   #:with-backend/.acos
   #:with-backend/.asin!
   #:with-backend/.asin
   #:.atan!
   #:.tan!
   #:.atan
   #:.tan
   #:use-backend/.tan!
   #:use-backend/.tan
   #:use-backend/.atan!
   #:use-backend/.atan
   #:get-backend/.tan!
   #:get-backend/.tan
   #:get-backend/.atan!
   #:get-backend/.atan
   #:get-backends/.atan!
   #:get-backends/.atan
   #:get-backends/.tan!
   #:get-backends/.tan
   #:with-backend/.atan!
   #:with-backend/.atan
   #:with-backend/.tan!
   #:with-backend/.tan
   #:with-backend/mae
   #:get-backends/mae
   #:get-backend/mae
   #:use-backend/mae
   #:.atan2
   #:.atan2!
   #:use-backend/.atan2
   #:use-backend/.atan2!
   #:get-backend/.atan2
   #:get-backend/.atan2!
   #:get-backends/.atan2
   #:get-backends/.atan2!
   #:with-backend/.atan2
   #:with-backend/.atan2!
   #:.square
   #:.square!
   #:.cube
   #:.cube!
   #:.log10
   #:.log10!
   #:use-backend/.log10!
   #:use-backend/.log10
   #:get-backend/.log10!
   #:get-backend/.log10
   #:get-backends/.log10!
   #:get-backends/.log10
   #:with-backend/.log10!
   #:with-backend/.log10
   #:.log2
   #:.log2!
   #:with-backend/.log2
   #:with-backend/.log2!
   #:get-backends/.log2 
   #:get-backends/.log2!
   #:use-backend/.log2
   #:use-backend/.log2!
   #:.log1p
   #:.log1p!
   #:use-backend/.log1p!
   #:use-backend/.log1p
   #:get-backend/.log1p!
   #:get-backend/.log1p
   #:get-backends/.log1p
   #:get-backends/.log1p!
   #:with-backend/.log1p
   #:with-backend/.log1p!
   #:save-tensor
   #:load-tensor
   #:arange
   #:linspace))
   
(defpackage #:nnl2.hli.ts.linalg
  (:use #:cl)
  (:export 
   #:svd
   #:diag
   #:luf
   #:eye
   #:eye-like))  
   